/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.owatonnarobotics;

import java.io.IOException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import jxl.read.biff.BiffException;
import jxl.write.WriteException;

/**
 *
 * @author Eson
 */
public class LoginPopup extends javax.swing.JFrame {

    /**
     * Creates new form LoginPopup
     * @param user the user that is signing in
     */
    public LoginPopup(User user) {
        initComponents();
        this.getRootPane().setDefaultButton(inOutButton);
        
        this.user = user;
        this.calendar = new GregorianCalendar();
        
        setLabels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inOutButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        fNameLabel = new javax.swing.JLabel();
        lNameLabel = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        timeWeekLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Log In/Out");
        setAlwaysOnTop(true);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setResizable(false);

        inOutButton.setText("Out");
        inOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inOutButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        fNameLabel.setText("First Name");

        lNameLabel.setText("Last Name");

        timeLabel.setText("Time: 12:12");

        timeWeekLabel.setText("X hours");

        jLabel1.setText("First Name:");

        jLabel2.setText("Last Name:");

        jLabel3.setText("Time Today:");

        jLabel4.setText("Total Time:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(timeWeekLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fNameLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lNameLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(timeLabel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fNameLabel)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNameLabel)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeLabel)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeWeekLabel)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inOutButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void inOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inOutButtonActionPerformed
        if(inOutButton.getText().equals("Out")){
            try {
                ExcelManager.setTotalWorkTime(user, totalWorkTime);
                LoginManager.signOut(user.getId());
                this.dispose();
            } catch (IOException | BiffException | WriteException ex) {
                Logger.getLogger(LoginPopup.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else if(inOutButton.getText().equals("In")){
            try {
                LoginManager.signIn(user.getId(), currentTimeMinutes());
                this.dispose();
            } catch(IOException ex) {
                Logger.getLogger(LoginPopup.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_inOutButtonActionPerformed
    
    private void setLabels(){
        fNameLabel.setText(user.getFirstName());
        lNameLabel.setText(user.getLastName());
        
        String formatTime = Integer.toString(calendar.get(Calendar.MINUTE));
        if(formatTime.length() < 2){
            formatTime += "0";
        }
        
        // If there are minutes (not just hours), set the String to those minutes
        timeWeekLabel.setText(prettyTime(user.getTotalTime()));
        
        try {
            if(LoginManager.userSignedIn(user.getId())){
                inOutButton.setText("Out");
                int loginTime = LoginManager.getInTime(user.getId());
                totalWorkTime = currentTimeMinutes() - loginTime;
                timeLabel.setText(prettyTime(totalWorkTime));
            }
            else{
                inOutButton.setText("In");
                timeLabel.setText("0H 0M");
            }
        } catch (NullPointerException ex) {
            try {
                // If user doesn't exist in properties, create new user logged out
                LoginManager.createUser(user.getId());
                inOutButton.setText("In");
                timeLabel.setText("0H 0M");
            } catch (IOException ex1) {
                Logger.getLogger(LoginPopup.class.getName()).log(Level.SEVERE, null, ex1);
                inOutButton.setText("Error");
            }
        } catch (IOException ex) {
            Logger.getLogger(LoginPopup.class.getName()).log(Level.SEVERE, null, ex);
            inOutButton.setText("Error");
        }
    }
    
    private int currentTimeMinutes(){
        return calendar.get(Calendar.HOUR_OF_DAY) * 60 + calendar.get(Calendar.MINUTE);
    }
    
    private String prettyTime(int time){
        String minutes = time % 60 + "M";
        return Integer.toString(time / 60) + "H " + minutes;
    }
    
    private User user;
    private GregorianCalendar calendar;
    private int totalWorkTime;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel fNameLabel;
    private javax.swing.JButton inOutButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lNameLabel;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JLabel timeWeekLabel;
    // End of variables declaration//GEN-END:variables
}
